### ISSUE TITLE
Add number of confirmations to block

### ISSUE THREAD

**Issue by ey51** [kaspanet/kasparov#44]
# Current state
block object doesn't include a field with the number of confirmations.
because of that, it is hard to understand which blocks are blue and which are red.

# Proposed change
block object should include a field with the number of confirmations.
block.confirmations = dag.selected_tip.blue_score - block.accepting_block.blue_score + 1

**Comment by ey51** [comment]
resolved.

**Comment by aspect** [comment]
@ey51 - this is not resolved.  the API always shows confirmations: `0`

Albeit IMHO, a block should not contain a confirmation field.  I would remove this from the API.
